// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhO-Pgatp_jPNH9i6NFjXKCNAgG1yPMgI',
    appId: '1:889289802965:web:ee8ac63011d7416a034e5c',
    messagingSenderId: '889289802965',
    projectId: 'hpp-tax-center',
    authDomain: 'hpp-tax-center.firebaseapp.com',
    storageBucket: 'hpp-tax-center.appspot.com',
    measurementId: 'G-M6NWG06132',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUODHB0ZGoPB2SYOgbs3dEEPFPjZSN8vI',
    appId: '1:889289802965:android:357b8f4b525a2306034e5c',
    messagingSenderId: '889289802965',
    projectId: 'hpp-tax-center',
    storageBucket: 'hpp-tax-center.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwkHBkKIEb7jVst0qhe0Ltg4cxqVf3q3A',
    appId: '1:889289802965:ios:613f78d17ef2522e034e5c',
    messagingSenderId: '889289802965',
    projectId: 'hpp-tax-center',
    storageBucket: 'hpp-tax-center.appspot.com',
    iosBundleId: 'com.example.hppTaxCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwkHBkKIEb7jVst0qhe0Ltg4cxqVf3q3A',
    appId: '1:889289802965:ios:613f78d17ef2522e034e5c',
    messagingSenderId: '889289802965',
    projectId: 'hpp-tax-center',
    storageBucket: 'hpp-tax-center.appspot.com',
    iosBundleId: 'com.example.hppTaxCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhO-Pgatp_jPNH9i6NFjXKCNAgG1yPMgI',
    appId: '1:889289802965:web:374f317acff011d3034e5c',
    messagingSenderId: '889289802965',
    projectId: 'hpp-tax-center',
    authDomain: 'hpp-tax-center.firebaseapp.com',
    storageBucket: 'hpp-tax-center.appspot.com',
    measurementId: 'G-7GCXWGN3BG',
  );
}
